queue_rules:
  - name: default
    update_method: merge
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=test
      - status-success=percy/daveshepherd.github.io
    merge_method: squash
    commit_message_template: |-
      {{ title }} (#{{ number }})

      {{ body }}
pull_request_rules:
  - name: Automatic merge on approval and successful build
    actions:
      delete_head_branch: {}
      queue:
        name: default
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(do-not-merge)
      - status-success=build
      - status-success=test
      - status-success=percy/daveshepherd.github.io
  - name: Automatic approval for projen upgrade pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=build
      - status-success=test
      - status-success=percy/daveshepherd.github.io
    actions:
      review:
        type: APPROVE
        message: Automatically approving projen upgrade