shared:
  ci_passed: &ci_passed
    - status-success=build
    - status-success=test
    - or:
        - status-success=percy/daveshepherd.github.io
        - status-success=snapshot-skipped

merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: default
    batch_size: 1
    update_method: merge
    queue_conditions:
      - -label~=(do-not-merge)
      - and: *ci_passed
    merge_method: squash
    commit_message_format:
      title: pr-title
      body: pr-body

pull_request_rules:
  - name: Queue PRs when approved or labelled
    conditions:
      - or:
          - "#approved-reviews-by>=1"
          - label=queue
    actions:
      queue:
        name: default
  - name: Queue Dependabot PRs
    conditions:
      - author=dependabot[bot]
    actions:
      queue:
        name: default

merge_protections_settings:
  reporting_method: deployments
