# Site settings
title: Dave Shepherd
description: > # this means to ignore newlines until "baseurl:"
  Dave is a software engineer specialising in enterprise Java, with an keen interest in a variety of technologies and development practices, including web technologies, application architecture and agile development.
baseurl: ""
url: "http://daveshepherd.uk"
linkedin_username: dashepherd
github_username: daveshepherd
medium_username: dave.shepherd
future: true

# Build settings
markdown: kramdown
paginate: 10
permalink: 2013-10-experts-sharing-their-insights-other-disciplines-needs-be-new-norm
permalink: /:year-:month-:title
